name: Build lib main

on:
  push:
    branches:
      - main

env:
  # Set version numbering scheme for the library
  ORG_GRADLE_PROJECT_version: 1.0.${{ github.run_number }}

jobs:
  build:
    name: Build, analyze and publish
    # Use 'self-hosted' if the build requires any internal resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          # Set correct Java version
          java-version: '16'
          distribution: 'adopt'
          cache: 'gradle'
      - name:  Build
        # Set correct build command
        run: ./gradlew build sonarqube
        env:
          # Used for accessing Protector package repositories on GitHub
          PROTECTOR_GITHUB_USER: ${{ secrets.PROTECTOR_GITHUB_MACHINE_USER }}
          PROTECTOR_GITHUB_TOKEN: ${{ secrets.PROTECTOR_GITHUB_MACHINE_TOKEN }}
          # Used for accessing SonarCloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          # Set paths to library jar files
          path: |
            build/libs/*.jar
      - name: Publish
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
