name: Build branches

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build and analyze
    # Use 'self-hosted' if the build requires any internal resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          # Set correct Java version
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build
        # Set correct build command
        run: ./gradlew build sonarqube
        env:
          # Used for accessing Protector package repositories on GitHub
          PROTECTOR_GITHUB_USER: ${{ secrets.PROTECTOR_GITHUB_MACHINE_USER }}
          PROTECTOR_GITHUB_TOKEN: ${{ secrets.PROTECTOR_GITHUB_MACHINE_TOKEN }}
          # Used for accessing SonarCloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
